### ISSUE TITLE
Config Tool on Udoobuntu2 RC1

### ISSUE THREAD

**Issue by macharborguy** [ektor5/udooconfig#2]
The config tool does not appear to be included with Udoobuntu2 RC1.  Running the current tool available here, attempting to change the GPU Video Memory usage results in the follow error...

Open App > Go to "UBoot" option, go to "Change RAM memory layout" option > "fw_printenv not found"

**Comment by ektor5** [comment]
The tool isn't compatible with UDOOBuntu RC1.
Also, the Vivante driver included in kernel 3.14 uses dynamic allocation, so it doesn't need previous configuration.

BR,
Ek5
